#
# TPA OIDC Clients Secret
#
#   This secret contains the OIDC client credentials needed by TPA.
#   It is populated by looking up the secret created by the tsf-iam chart
#   and copying it to the TPA namespace.
#
{{- $tpa := .Values.trustedProfileAnalyzer -}}
{{- $oidcClientsSecretName := "tpa-realm-clients" }}
{{- $oidcSecretNamespace := "tsf" }}

{{- $oidcSecretObj := (lookup "v1" "Secret" $oidcSecretNamespace $oidcClientsSecretName) | default dict }}
{{- $oidcSecretData := (get $oidcSecretObj "data") | default dict }}

{{- if $oidcSecretData }}
---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ $oidcClientsSecretName }}
  labels:
    app.kubernetes.io/name: tpa-oidc-clients
    app.kubernetes.io/part-of: trustify
type: Opaque
data:
  {{- range $k, $v := $oidcSecretData }}
  {{ $k }}: {{ $v }}
  {{- end }}
{{- end }}
